# @package _global_

defaults:
  - override /dataset: amazon_ratings.yaml

runs: 10
trial_dir: partition_eval

dataset:
  expert_id: 0
  num_experts: 3
  fraction: 0.5
  group: homophily

train:
  epoch: 2500
  lr: 0.0005

model:
  name: GCNII
  hidden_dim: 512
  init_layers: 0
  conv_layers: 2
  norm: layer
  out_norm: false
  init_dropout: 0
  dropout: 0.5
  jk: last
  residual: sum
  theta: null
  layer: null
  cached: true
  alpha: 0.1
  shared_weights: false