# @package _global_

defaults:
  - override /dataset: amazon_ratings.yaml

runs: 10
trial_dir: partition_eval

dataset:
  expert_id: 2
  num_experts: 3
  fraction: 0.35
  group: homophily
  use_test: false

train:
  epoch: 2500
#  lr: 5e-05
  lr: 0.0001

model:
  name: GCN
  hidden_dim: 256
  init_layers: 1
  conv_layers: 2
  norm: layer
  out_norm: false
  init_dropout: 0.2
#  dropout: 0.5
  dropout: 0.2
  dropedge: 0
  jk: attn
  residual: null
  adj_norm: rw