# @package _global_

defaults:
  - override /dataset: flickr.yaml

runs: 10
trial_dir: partition_eval

dataset:
  expert_id: 2
  num_experts: 3
  fraction: 0.35
  group: homophily
  use_test: false

train:
  epoch: 700
  lr: 0.005
  early_stopping: -1
model:
  name: GCN
  hidden_dim: 256
  init_layers: 1
  conv_layers: 2
  norm: batch
  out_norm: false
  adj_norm: rw
  init_dropout: 0.2
  dropout: 0.6
  jk: null
  residual: cat