# @package _global_

defaults:
  - override /dataset: flickr.yaml

runs: 10

log_logit: false

train:
  epoch: 500
  lr: 0.001

model:
  name: GCNII
  hidden_dim: 256
  init_layers: 0
  conv_layers: 4  # hops
  norm: batch  # layer, batch
  out_norm: false  # l2 norm
  init_dropout: 0.5
  dropout: 0.5
  jk: null  # cat
  residual: null  # sum, incep

  shared_weights: false
  alpha: 0.1
  theta: 1.5  # 0, 0.5, 1.0, 1.5
  cached: true  # only for transductive setting