# @package _global_

defaults:
  - override /dataset: penn94.yaml

runs: 10
trial_dir: partition_eval

dataset:
  expert_id: 0
  num_experts: 3
  fraction: 0.35
  group: homophily
  use_test: false

train:
  epoch: 700
  lr: 0.0005
  weight_decay: 0.0001

model:
  name: GCN
  hidden_dim: 32
  init_layers: 1
  conv_layers: 2
  norm: layer
  out_norm: false
  adj_norm: rw
  init_dropout: 0.2
  dropout: 0.6
  jk: last
  residual: sum