# @package _global_

defaults:
  - override /dataset: penn94.yaml

runs: 10
trial_dir: partition_eval

dataset:
  expert_id: 0
  num_experts: 2
  fraction: 0.5
  group: homophily

train:
  epoch: 700
  lr: 0.005

model:
  name: MIXHOP
  hidden_dim: 64
  init_layers: 0
  conv_layers: 2
  norm: batch
  out_norm: false
  init_dropout: 0.2
  dropout: 0.2
  jk: null
  residual: null
  powers:
  - 0
  - 1
  - 2