# @package _global_

defaults:
  - override /dataset: pubmed.yaml

runs: 10
trial_dir: partition_eval

dataset:
  expert_id: 0
  num_experts: 3
  fraction: 0.35
  group: homophily

train:
  epoch: 700
  lr: 0.001
  early_stopping: -1
model:
  name: GCN
  hidden_dim: 256
  init_layers: 0
  conv_layers: 2
  norm: batch
  out_norm: false
  adj_norm: rw
  init_dropout: 0.2
  dropout: 0.2
  jk: last
  residual: cat