# @package _global_

defaults:
  - override /dataset: actor.yaml

runs: 10

dataset:
  undirected: false

train:
  epoch: 1000
  lr: 0.01

model:
  name: FABER
  hidden_dim: 512
  init_layers: 0
  conv_layers: 3
  norm: layer
  out_norm: false
  init_dropout: 0
  dropout: 0.3
  dropedge: 0
  jk: attn
  residual: cat

  dir_alpha: 0.5
  k_plus: 2
  weight_penalty: null
  exponent: -0.5
  zero_order: false