# @package _global_

defaults:
  - override /dataset: actor.yaml

runs: 10

dataset:
  undirected: false

train:
  epoch: 1000
  lr: 0.005

model:
  name: DIRGCN
  hidden_dim: 512
  init_layers: 0
  conv_layers: 3
  norm: layer
  out_norm: false
  init_dropout: 0
  dropout: 0.
  dropedge: 0
  jk: last
  residual: cat

  dir_alpha: 0.5