# @package _global_

defaults:
  - override /dataset: computers.yaml

runs: 10

log_logit: false


dataset:
  ptb_type: null
  ptb_ratio: 0
  name: computers
  train_rate: 0.6
  val_rate: 0.2
train:
  epoch: 1000
  lr: 0.0005
  weight_decay: 0.001
  early_stopping: -1
  grad_norm: null
  use_adamw: true
  train_mask_rate: 1
  use_label: false
model:
  name: GCN
  hidden_dim: 512
  init_layers: 1
  conv_layers: 3
  norm: layer
  out_norm: false
  init_dropout: 0.1
  dropout: 0.6
  dropedge: 0.1
  jk: attn
  residual: null
  adj_norm: sym
