# @package _global_

defaults:
  - override /dataset: pubmed.yaml

runs: 10

log_logit: false

train:
  epoch: 1000
  lr: 0.0005

model:
  name: GAT
  hidden_dim: 256
  init_layers: 0
  conv_layers: 2  # hops
  norm: batch  # layer, batch
  out_norm: false  # l2 norm
  init_dropout: 0.5
  dropout: 0.5
  jk: null  # cat
  residual: null  # sum, incep

  heads: 2
  edge_dropout: 0.1
  attn_dropout: 0.
  symmetric_norm: false

  ###########################
  # Comments:
  # Test: 0.5532
  #
  # Important Param:
  # - heads
