# @package _global_

defaults:
  - override /dataset: pubmed.yaml

runs: 10

log_logit: false

train:
  epoch: 500
  lr: 0.01

model:
  name: GCN
  hidden_dim: 512
  init_layers: 0
  conv_layers: 2  # hops
  norm: layer  # layer, batch
  out_norm: false  # l2 norm
  init_dropout: 0.1
  dropout: 0.3
  jk: null  # cat
  residual: null  # sum, incep