# @package _global_

defaults:
  - override /dataset: snap-patents.yaml

runs: 10

log_logit: false

train:
  epoch: 2000
  lr: 0.0005
#  weight_decay: 1e-3
  weight_decay: 0
  early_stopping: -1

model:
  name: DIRGCN
  hidden_dim: 32
  init_layers: 0
  conv_layers: 5
  norm: null  # layer, batch
  out_norm: true  # l2 norm
  init_dropout: 0.
  dropout: 0.
  jk: max  # cat, max
  residual: cat  # sum, incep

  dir_alpha: 0.5