# @package _global_

defaults:
  - override /dataset: snap-patents.yaml

runs: 10

dataset:
  undirected: true

train:
  epoch: 2000
  lr: 0.005

model:
  name: GCN
  hidden_dim: 32
  init_layers: 0
  conv_layers: 5
  norm: batch
  out_norm: false
  init_dropout: 0.1
  dropout: 0.
  dropedge: 0
  jk: last
  residual: cat
  adj_norm: sym