# @package _global_

defaults:
  - override /dataset: wikics.yaml

runs: 10

dataset:
  ptb_type: null
  ptb_ratio: 0
  name: wikics
  train_rate: null
  val_rate: null
train:
  epoch: 1000
  lr: 0.0005
  weight_decay: 0
  early_stopping: -1
  grad_norm: null
  use_adamw: true
  train_mask_rate: 1
  use_label: false
model:
  name: GCN
  hidden_dim: 128
  init_layers: 1
  conv_layers: 2
  norm: layer
  out_norm: false
  init_dropout: 0.1
  dropout: 0.7
  dropedge: 0
  jk: attn
  residual: null
  adj_norm: rw
