# @package _global_

defaults:
  - override /dataset: wikics.yaml

runs: 10


dataset:
  ptb_type: null
  ptb_ratio: 0
  name: wikics
  train_rate: null
  val_rate: null
train:
  epoch: 1000
  lr: 0.001
  weight_decay: 0
  early_stopping: -1
  grad_norm: null
  use_adamw: true
  train_mask_rate: 1
  use_label: false
model:
  name: GAT
  hidden_dim: 256
  init_layers: 1
  conv_layers: 3
  norm: layer
  out_norm: false
  init_dropout: 0.2
  dropout: 0.5
  dropedge: 0
  jk: attn
  residual: null
  heads: 1
  adj_norm: sym
